export { remove } from './remove'
export { wipeDisk } from './wipeDisk'
export * as fileMethods from './file'
export * as dirMethods from './dir'
export { standards } from './standards'
export { eventEmitter } from './events'
